import = ["/home/nejern/.config/alacritty/themes/gruvbox_material.toml"]

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.normal]
family = "MesloLGS NF"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.95
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 0
lines = 0
